// Alle tabel- en veld-ids van de base "Bon Bini uren en OT" op een plek.
//
// Waarom dit bestand bestaat: tot nu toe stond in elke functie zijn eigen lijstje
// veld-ids. Wie een veld hernoemt of de base ooit vervangt, moet dan door alle
// functies heen. Vanaf nu haalt elke module zijn ids hier op, en verder nergens.
//
// Regel: hier staan alleen ids en namen. Geen logica, geen fetch, geen Airtable.
// De enige plek die met Airtable praat is lib/data.mts.

export const BASE = "app4HQkMqFpZCnqpv";

export const T = {
  crew: "tblpaxWdwaY6XbPbT",
  uren: "tblRxNpruBfkT5NR3",
  draaidagen: "tblMsE819GouzsTCo",
  weekstaat: "tblc33QhfS91Jx98w",
  regelset: "tbljCvRiFsZav6XbL",
  beschikbaarheid: "tblqgRm8q2MH7gU4l",
  decors: "tbljinqf7KnDAJ2dc",
  locatiekandidaten: "tbldTqBvnxfLcHUZI",
  locatiereacties: "tblkbS3gyg6YewYjK",
  sceneplanning: "tblGNMnWzaDEApj9x",
} as const;

export const CREW = {
  naam: "fldypfInaNvNURVID",
  crewId: "fldLxzaUyiimBaCP7",
  voornaam: "fldx9Z5jB6cx4gc8W",
  achternaam: "fld62PpLra6zgLurN",
  functie: "fld9EwU9tcPC3Rd70",
  departement: "fld5ZowTYCml5Ktf0",
  contracttype: "fldA6vBae8jrm3Zgk",
  email: "fldClEi5WxnJfpmFI",
  dagprijs: "fld1LOYLGgIt8AHeH",
  uurprijs: "fldoqBqzvPE2Tbj6R",
  maandfee: "fld20uyjjkp4I6Ce8",
  kmTarief: "fld2BrRp6HJm8KAia",
  groot: "fld5MNLx0vqEeMxRG",
  otRegelset: "fldmgj93afhMKBD0q",
  overurenAfgesproken: "fldamorHOYRnLOXNI",
  nietMeerOpProductie: "fldl49e40hA0LnwF9",
  doetNietMeeMetUren: "fldiBe898AEQaHfGB",
  straat: "fld4RbRodT64ygSrj",
  postcode: "fldkr0cwaheZ2HLvJ",
  woonplaats: "fldovdqOJP57WQJAn",
  telefoon: "fld7LtKIiMKj4xfim",
  geboortedatum: "fld5F3CDLms40MO40",
  allergieen: "fldm1Sukst1SULIhk",
  bhv: "fldb6VpPeqP7PnVLI",
  noodcontact: "fldeW4VpRIlVGIw08",
  kenteken: "fld7rf2FIQRRXJRId",
  vastVertrekpunt: "fldTEKWR0XnJSnwFb",
  coordinaten: "fldfv9BQZqNffgxPk",
  contractvorm: "fld3ERMdFZjaxsnla",
  bedrijfsnaam: "fld9nOwploKcRCzI0",
  btw: "fldJbzQ2lfXo1IOnM",
  kvk: "fld2LgX6Wdv9nzy5V",
  payrollsysteem: "fldM2pgUkn7TwwH8T",
  iban: "fldMMHGk6JMCyJkVU",
  contractBron: "fldm5aSv8bQ1HFWdk",
  contractRev: "fldJW77B5NKTXsAI9",
  contractControleren: "fld4sKmm9OB7tcil3",
  contractmelding: "fldqgirzkqiX1J6Vk",
  urenlink: "fld7EKZuZaQj5l3F1",
  gegevenslink: "fldFbUMDeiJ7lQfdq",
  portaltoken: "fldQntV7mektL0i94",
  uitnodigingVersturen: "fldaKBdROkZ0HTTPM",
  uitnodigingVerstuurd: "fldQloj5QW1obxSFs",
  startmail: "fldXcX16qUjGrmG1D",
  startmailWeek: "fldDtc4DDKdqjEBxR",
  herinnering: "fldPop8xTY8qEfDG2",
  herinneringWeek: "fldmPTe2fTgX5OUmU",
  stuurWeekoverzicht: "fldbyqBPJdyTlllQI",
  weekoverzichtTekst: "flda9BHKOkNj9HWTP",
  demo: "fldLJhe646qhHzIdt",
} as const;

export const UUR = {
  registratie: "fldMeqRcR0Skjde27",
  crew: "fldfvmiXAJs7zwkR5",
  datum: "fldUJUogwUXJcHjUY",
  start: "fldU2bM0zgwzdT0bm",
  eind: "fld6AlZUx8KdMQ3C2",
  pauze: "fldSMeHoGNVfawmK5",
  setlocatie: "fldpS0lkLP9hVCo8G",
  nacht: "fldTjhNf1lgUbVLqS",
  zondag: "fldPjJGAM322yOG84",
  nietGewerkt: "fldZZUJl3ypFGL4Zz",
  status: "fldmbytC1V67nTCRP",
  pmAkkoord: "fldhSAOW9kSSLtq2O",
  weeknummer: "fld10MS4SEz5YQmru",
  opmerking: "fldTfGqTN0FO8enHy",
  reisHeenVertrek: "fldomLqJKHZB3oaLX",
  reisHeenAankomst: "fld94kABPxWfagFWt",
  reisTerugVertrek: "fldR1UXD8sGE2S6TO",
  reisTerugLoods: "fldoZ8mVhBmuliV6i",
  reisTerugThuis: "fldOR7mWENFPeWoO0",
  vervoer: "fldnWjYdxj2xunynp",
  vertrekpunt: "fldbubsPSTnUhvGig",
  anderVertrekadres: "fld7OAt0bomxfAg0u",
  km: "fldzPYCwC6zYtEf7A",
  kmBerekend: "fldzro4YTlUMBUos5",
  kmTarief: "fldsiJjyYqxQ22GGu",
  kmPersonen: "fldfG07rxz7WIntqD",
  kmMateriaal: "fldQIKWm9BOPTjFoO",
  parkeer: "fldVHtOvArO6C7ohO",
  preCall: "flduy2J3aeaf3aAA4",
  afbouw: "fldBqCagLEIbtMskP",
  extraReden: "fldUMEiTL4OBJ4sBl",
  extraMinuten: "fldSjTLzFCmqDnreJ",
  gewerkteUren: "fldeNWcX5bzIORgZG",
  otUren: "fld2adlJTn1P3fFXI",
  otBedrag: "fldvZth9eAmhoXSNE",
  nachtUren: "fldcgEBnJzreVVCOC",
  nachtBedrag: "flddZ7GiVKbHhJOOr",
  reisuren: "fldsPGZPwrfTQPDH4",
  reisBedrag: "fldisHsBQakZveohi",
  taUren: "fld8xnBSCobVnrucW",
  taBedrag: "fldB7d9cN1rFnuJAK",
  zondagBedrag: "fld46LhdbAUP2I5pD",
  kmBedrag: "fldpAEURNJaiG1IpK",
  totaal: "fld5onf7FZPWLvmHH",
  dagprijsContract: "fldzQPwVnTfz1if4h",
  uurprijsContract: "fld6zfmC918siFZri",
  demo: "fld0E33TnSOPTpDwu",
} as const;

export const DAG = {
  naam: "fldFPwQFhQg9m8OO3",
  datum: "fldc7rNjjJ2tWf6HH",
  dd: "fldHBwrNl0FsgtwGG",
  blok: "fldiFfFuKr0XcBsSY",
  crewcall: "fldffFdKT94egqOqO",
  wrap: "flddrin96UeGaVvNA",
  lunch: "fld9U5l9EkPqa1id7",
  locatie: "fldO5VdxPm965Fd6P",
  setadres: "fldofXLLEY8m9sFsi",
  hotel: "fldXBWRWoyggKJNug",
  coordinatenSet: "fld51k1JqqFLe8rEY",
  afstandSet: "fldpYy8XjZG2UBrFD",
  nacht: "fldCfhVnog1LVeFcQ",
  zondag: "fldQuMgnrDlXf62WH",
  crewAanwezig: "fldj8DzIUu8NCOnyj",
  crewOpCallsheet: "fldB2LljUvMl7OOrF",
  bron: "fldeaQP5jyM12AmMP",
  rev: "fldXcO3cTd4PN4Z8K",
  controleren: "fldB1MM160pbzJtrg",
  leesmelding: "fldPR9hTpeswJ5Csx",
  invullink: "fldowzWgwxGLV9tBL",
  demo: "fldI7JvVi14CDiVP9",
} as const;

export const WEEK = {
  naam: "fld7jQwp4UrxECR37",
  crew: "fldVoJDrqsKQktUxE",
  weeknummer: "fld3fVG7AlqofJ0Bv",
  jaar: "fldGfR7SPCbU6MudM",
  gewerkteUren: "fldIPBP7e0ZpF44Q1",
  otBedrag: "fldNqyqvFYQwhjtBQ",
  nachtBedrag: "fldIW0lMlXlm6rrnx",
  reisBedrag: "fldpRh9nhEFkaYk9c",
  taBedrag: "fldFTGzp5TDxBDeaJ",
  zondagBedrag: "fldU429sHjukwlDf6",
  kmBedrag: "fldOWwJKxFk0N8Igy",
  parkeer: "fldx97EUR7cczgSrr",
  totaal: "fld6EaQxEqgUhPv7B",
  pmAkkoord: "fldXTfSzNzISd1X09",
  status: "fldxzJIEb05HhAxY2",
  afgetiktDoor: "fldMtC6TXtZ3GMU3V",
  opmerking: "fldYyHqO1RZ8Wz7ve",
  crewEmail: "fldpl6fZfSLaCM1f5",
  urenlink: "fldXJ92A3kNzOOpo4",
} as const;

export const REGELSET = {
  naam: "fldK7ZFdvu4B8JaJq",
  normaleDraaiuren: "fldsMvFonrsCg91m4",
  lunchMinuten: "fld5MTpdHDMJhdIHi",
  otPct1: "fld8HMkpBQIDjMtAM",
  otPct5: "fldEpQ56iL5GNfmHL",
  reistijdVrijUren: "fldsjAAzb0EbSmGFq",
  reistijdOtPct: "fldxJrfUosrpdSpXg",
  nachtStart: "fldPbgKTdhKvEVV4g",
  nachtEind: "flddAzFvvY8X18UQ4",
  nachtPct: "fldqfNYlllGUojDIP",
  vrijeNachtenPct: "fldoPPHOeyTfzrdI3",
  kmPersonen: "fldH4eEThMdxIxtUV",
  kmMateriaal: "fldHj2pyAEjcafzgy",
  turnaroundMinUren: "fldXLxUPSdc7tmAV7",
  weekendTurnaroundUren: "fld7WOTppRJQxa42L",
  turnaroundPct: "fldlV7oYDOyCzTL9Q",
  zondagPct: "fldm7SZSz3Q6WXozE",
  zondagVrijPct: "fldtdCpvf9RX60csT",
  zesdeDagPct: "fldNFY5WcMaBmrCmQ",
  zevendeDagPct: "fldTlTb2r8ZdF1IlT",
  geplandeDraaidagen: "fldMJpmH9dQBSqjGW",
  geplandeDraaidagenNL: "fldDoLCobSg4rolH0",
  geplandeDraaidagenOOS: "fldcocHYfdoPWgyO7",
  stapelenToestaan: "fldweiL1CvD7iXx4F",
  bron: "fldlbCT7jPsLzXmPy",
  wrapKnop: "fldV7ZOIDnA9MRj6x",
  testdatum: "fldIZ4WeM3no1pgXA",
} as const;

export const BESCHIKBAAR = {
  registratie: "fldXEk2WOd5I238KM",
  crew: "fldRGdqT4zgOZmCrf",
  van: "fldLEalWVtlRgoujH",
  totEnMet: "flde3xlGAZaeryIm3",
  status: "fldC1BzFK3r2LOdOf",
  vanTijd: "fldOdorkFGviqH7FQ",
  totTijd: "fldSoMOUaCBek2edU",
  toelichting: "fldPp9jWTGY6fKx1X",
} as const;
